In [2]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup

In [3]:
olympic_athletes_medal = pd.read_csv("/Users/lizethmendoza/Documents/STAT 281/olympics-data-story/olympics.csv")
sum_winter_1896_2022 = pd.read_csv("/Users/lizethmendoza/Documents/STAT 281/olympics-data-story/olympic_medals.csv")
tokyo_2020 = pd.read_csv("/Users/lizethmendoza/Documents/STAT 281/olympics-data-story/2020_Olympics_Dataset.csv", encoding='ISO-8859-1')
beijing_2022 = pd.read_csv("/Users/lizethmendoza/Documents/STAT 281/olympics-data-story/beijing_Olympic_athlete_profile.csv")

In [13]:
olympic_athletes_medal.head()

,id,name,sex,age,height,weight,team,noc,games,year,season,city,sport,event,medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [14]:
sum_winter_1896_2022.head()

,discipline_title,slug_game,event_title,event_gender,medal_type,participant_type,participant_title,athlete_url,athlete_full_name,country_name,country_code,country_3_letter_code
0,Curling,beijing-2022,Mixed Doubles,Mixed,GOLD,GameTeam,Italy,https://olympics.com/en/athletes/stefania-cons...,Stefania CONSTANTINI,Italy,IT,ITA
1,Curling,beijing-2022,Mixed Doubles,Mixed,GOLD,GameTeam,Italy,https://olympics.com/en/athletes/amos-mosaner,Amos MOSANER,Italy,IT,ITA
2,Curling,beijing-2022,Mixed Doubles,Mixed,SILVER,GameTeam,Norway,https://olympics.com/en/athletes/kristin-skaslien,Kristin SKASLIEN,Norway,NO,NOR
3,Curling,beijing-2022,Mixed Doubles,Mixed,SILVER,GameTeam,Norway,https://olympics.com/en/athletes/magnus-nedreg...,Magnus NEDREGOTTEN,Norway,NO,NOR
4,Curling,beijing-2022,Mixed Doubles,Mixed,BRONZE,GameTeam,Sweden,https://olympics.com/en/athletes/almida-de-val,Almida DE VAL,Sweden,SE,SWE

In [21]:
tokyo_2020.head()

,Unnamed: 0,Code,Name,Gender,Age,NOC,Country,Discipline,Sport,Event,Rank,Medal
0,1,1346266,AALERUD Katrine,Female,26,NOR,Norway,CRD,Cycling Road,Women's Road Race,37.0,NaN
1,2,1346266,AALERUD Katrine,Female,26,NOR,Norway,CRD,Cycling Road,Women's Individual Time Trial,20.0,NaN
2,3,1355250,ABAD Nestor,Male,28,ESP,Spain,GAR,Artistic Gymnastics,Men's All-Around,NaN,NaN
3,4,1355250,ABAD Nestor,Male,28,ESP,Spain,GAR,Artistic Gymnastics,Men's Floor Exercise,NaN,NaN
4,5,1355250,ABAD Nestor,Male,28,ESP,Spain,GAR,Artistic Gymnastics,Men's Pommel Horse,NaN,NaN

In [16]:
beijing_2022.head()

,name,participating countries,game,Age,Gender,birth,Birth Country,Hobbies,Occupation,Education,...,Training,National league,Award,Previous names,Choreographer,Hand,Hero,Reason,Influence,Height (m/ft)
0,Marion THENAULT,Canada,Freestyle Skiing,21,Female,2000-04-09,Canada,Rock climbing and reading science-fiction.,"Athlete, student",Bachelor of Science (Aerospace Engineering) - ...,...,NaN,NaN,World Cup Tour Rookie of the Year (2021),NaN,NaN,NaN,"For aerials, Laura Peel (AUS). ""I have the cha...","""I live for adrenaline rushes. Aerials gives m...",Four-time NorAm aerials gold medallist and Can...,NaN
1,Sacha THEOCHARIS,France,Freestyle Skiing,31,Male,1990-11-19,France,"Golf, ski mountaineering, and backcountry skii...",Athlete,"Em Lyon Business School, Management. IUT Annec...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Drawn to the freedom the sport offered. (sach...,NaN,NaN
2,Edouard THERRIAULT,Canada,Freestyle Skiing,18,Male,2003-02-16,Canada,Skateboarding. (Instagram),Athlete,"Maximise center, Sainte-Agathe",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Broderick THOMPSON,Canada,Alpine Skiing,27,Male,1994-04-19,Canada,"Fly fishing, ukulele, wood carving, baseball, ...",Athlete,"Whistler Secondary School. (Athlete, 30 Jun 2021)",...,"""Get the most out of every training session. I...",NaN,Ski Canada Magazine Bursary (scholarship) from...,NaN,NaN,NaN,Alpine skier Bode Miller (USA): Six-time Olymp...,"Loves the speed, big air, and exhilarating fre...","""My community, family and older athletes like ...",NaN
4,Claire THOMPSON,Canada,Ice Hockey,24,Female,1998-01-28,Canada,NaN,Athlete,Received a bachelor's degree in Ecology and Ev...,...,NaN,NaN,Second Team All-Ivy (2020)Academic All-Ivy Lea...,NaN,NaN,Left,"Ice hockey player Courtney Birchard (CAN), wor...",NaN,NaN,1.73/5'8''